メインプログラムからテストデータを分離
thayashi131050/spring-batch-sample pull request #21
Opened 2020-06-01 02:14 UTC by sprngTst001

テストデータセットアップを行うアノテーションの追加
テストデータ定義ファイルを追加
fix #16

2020-06-01 15:46 UTC, thayashi131050 requested changes
`schema-all.sql`をtestに移動したことで、mainのプログラムで実行のたびに出力テーブルのデータが増えていく状態になっています。mainとtestはそれぞれ以下の役割で作成してください。
- main
  - `peopleInput`にあるデータを加工して`peopleOutput`に出力する
    - `peopleInput`のデータは事前に用意されている前提
  - `peopleOutput`は実行のたびに初期化する
    - 実行後は`peopleInput`に対するデータのみが`peopleOutput`に存在することを保証
- test
  - `peopleInput`のデータを用意する
  - `peopleOutput`の内容を検証する

また、`fix #16`は目的が異なるのでコミットを分けてください。
#17 に対するコミットには`close #17`を含めてください。

2020-06-01 15:46 UTC, thayashi131050 commented on src/test/resources/dbunit/expectedDataset1.xml
> +</dataset>
不要な空白で差分が発生しています。
`schema-all.sql`の指摘と一緒に対応お願いします。

2020-06-03 05:51 UTC, sprngTst001 commented
今まで取消して再度プルリクエストを投げていましたが、修正するだけでここに反映されるのですね...。分かりづらくしていたようで申し訳ないです。

2020-06-03 15:28 UTC, thayashi131050 approved these changes

2020-06-03 15:32 UTC, merged